### ISSUE TITLE
mezzanine 4.1 + autocomplete 2.3 + filer 1.1

### ISSUE THREAD

**Issue by frague59** [divio/django-filer#736] opened 2016-02-12 12:55 UTC
Hi, 
I'm facing a jQuery hell with mezzanine + autocomplete-light.

The constatations :
* I'm in a mezzanine admin change view, which has 
 * an autocomplete field 
 * a filer (image) field 
* The mezzanine left menu shows quickly, then it hides imself : is created, but I'm not able to view it. 
* The autocomplete field doen't not work : the actual value is shown, but I can't change it.
* The filer works perfectly... but I'm pretty sure it has taken the jquery namespace for himself...

`TypeError: $ is undefined`

If I load a jQ before the autocomplete_light/static.html I have another error : 
`TypeError: $(...).yourlabsWidget is not a function` 

I've tracked the jQ versions used, and autocomplete is loaded in a version on jQ, but launched (through $(document).ready()) through the filer version of jQ, the one from filer.
I've tried to noConflict the jQ before autocomplete loadings, but for none..

Could you help me with this issue ? Thanks for your help !

How can I

**Comment by frague59** [comment] 2016-02-22 07:46
Hi, 

I've some improvements about this issue : 
* I've moved the autocomplete initialization to the bottom of the page, and it work now, but I do not have the left menu. 
* The left menu still does not shows. If I disable the filer field in the change or create form, the left menu works : the problem really comes from filer. 

So I'm still stuck.

Has anybody the same issue ? How can I fix it ? Thanks !

**Comment by stefanfoulis** [comment] 2016-02-22 10:06
I personally have no experience with mezzanine. But I suspect this will be a problem with any other widget on the same admin form that uses jQuery.
It probably has to do with the visual updates done for 1.0 on django-filer. We used to avoid using jQuery in the filer widget completely (precisely out of this reason). But it might have been added as part of the visual updates.

@Flight do you know more?

**Comment by stefanfoulis** [comment] 2016-02-25 16:44
@frague59 we've been working on fixing a bunch of bugs related to the js loaded by the widget. Could you test with the develop branch to see if this issue was already resolved for you?
(/cc @lory87 )

**Comment by stefanfoulis** [comment] 2016-03-01 09:12
@frague59 would be cool if you could confirm if our latest changes fix the issue. :-)

**Comment by frague59** [comment] 2016-03-22 15:35
Hi, 
I'did just saw your message, and did update to  django-filer to 1.2:

`$ pip install django-filer -U`

I have the same issue. Could I help you ? How ?
Thanks !

**Comment by frague59** [comment] 2016-03-22 16:24
... I've tryed with the develepment branch of django-filer, and it seems to work for me.

**Comment by stefanfoulis** [comment] 2016-03-23 11:36
@frague59 thanks for testing.
Did this work with older versions of django-filer?
Maybe re-loading jquery kills the jquery stuff that the django-filer widget does. That is probably why the filer widget does not initialise.

**Comment by frague59** [comment] 2016-03-24 08:08
@stefanfoulis

hi, 

It worked with django-filer==1.1.1, the widget was showed, autocomplete worked too but the left menu were not displayed. 

The problem comes from filer loading jquery (1.11.3) unconditionally, overriding the site-level one. 
I'm currently loading 2.1.4 for tinymce.

Thanks !

**Comment by jokerejoker** [comment] 2016-03-29 14:10
I have the same error. I am not using mezzanine, but only autocomplete_light. My widgets show up perfectly fine, but I get the same JS error, and I to can trace it back to filer loading it's own version of jquery.

From what I have found the problem is with autocomplete light v2, which is no longer supported, where the JS jQuery is not scoped and therefor the yourlabsWidget function of jQuery does not exist on the loaded jQuery because filer override the jQuery object after the autocomplete light is initialized.

In my opinion the problem is with the code of autocomplete_light, but things like this only arises because filer as decided to load its own version of jQuery, which is, by my opinion a big design flaw, and will lead to more problems like this in the future.

**Comment by jokerejoker** [comment] 2016-03-29 14:21
@frague59 My fix for now is to simple provide an empty file replacing the filer/js/libs/jquery.min.js, and all works just fine.

**Comment by stefanfoulis** [comment] 2016-03-30 08:08
ok. I wonder if we can just piggy-back on the jQuery provided by django admin? Usually @lory87 would tackle this kind of problem. But she is currently tied up in project work. It would be really awesome if someone could put together a pull-request. :-)

**Comment by jokerejoker** [comment] 2016-03-30 08:30
@stefanfoulis I don't have enough insight in the filer JS code to conclude that the django admin privided jQuery 1.11.2 is sufficient, but one solution I can think of is to map the django-filer provided jQuery to a custom variable instead of the standard $-variable, by using the noconflict method, like django.admin does with the django.jQuery variable.

I will try to find to time to test this and if it works provide a pull-request, though I still think that the best solution would be to be using the django.jQuery, also to follow the Django guidelines of DRY programming which the current solution is in a bit of a conflict with. ;)

**Comment by lory87** [comment] 2016-04-01 13:22
@stefanfoulis @jokerejoker @frague59 working on this issue.

**Comment by lory87** [comment] 2016-04-05 07:19
@jokerejoker @frague59 I did some fixes and merged them to develop branch. Can you tell me please if this change fixes the issue?

**Comment by gradel** [comment] 2016-04-11 15:32
I'm also trying to integrate filer with mezzanine, since I use django-widgy which uses filer too.
Got to work with 1.1.1 by disabling the admin_filer.css completely. Using these styles makes not only the sidebar disappear, but changes the design in various places of the site, which is grappelli based.
Same with develop, but then selecting files is also broken.
For me it seems like admin_filer.css has too much an effect outside of just the admin file widget, where it is declared as media (in develop-branch), making filer unusable in other contexts. That's unfortunate, since its the best file and image app I know for django.

**Comment by lory87** [comment] 2016-04-15 09:59
@gradel We could determine the problem and are working on it. Thanks for your feedback. We will let you know when we merged changes to develop branch.

 /cc @stefanfoulis

**Comment by lory87** [comment] 2016-04-21 14:20
@gradel Issue is fixed and changes are merged to develop branch. Release is coming soon. Thank you for your feedback.

**Comment by gradel** [comment] 2016-04-21 14:36
Had a first look and you find me deeply impressed :)
Thanks a lot for this fantastic work!

**Closed** 2016-04-22 15:15 UTC
Labels: bug, regression

**Comment by lory87** [comment] 2016-04-25 07:25
@gradel Do you have any experience or do you know if mezzanine doesn't look on get parameters? Because search doesn't work there But parameter is correct.

**Comment by gradel** [comment] 2016-04-25 09:27
@lory87 Seems to work here, so I can't reproduce the issue so far:

![bildschirmfoto vom 2016-04-25 11 24 17](https://cloud.githubusercontent.com/assets/635870/14779494/a768cb22-0ad8-11e6-8467-0d1f4a280e06.png)

**Comment by lory87** [comment] 2016-04-25 09:59
@gradel  Thanks for your feedback. Maybe I missed something in config.
