### ISSUE TITLE
Blank page on popup

### ISSUE THREAD

**Issue by hersche** [divio/django-filer#588] opened 2015-09-11 17:59 UTC
Hello,

i've got a bug in combination with cmsplugins/djangocms - but i was able to resolve it here (at least to make it work again). Django is on version 1.8.

The way to resolve: Go into admin -> go editing a site -> open text-editor -> attach a filer-picture -> click the magnifier for files -> blank page instead of file-list.

original magnifier-link: /de/admin/filer/folder/last/?_to_field=file_ptr

the weird effect here is, that it isn't blank when copy pasted into another window.

anyway, my solution is on file

filer/templates/admin/filer/widgets/admin_file.html

Line 15: <a href="{{ lookup_url }}" replaced by <a href="/de/admin/filer/folder/1/list/?_popup=1"

Of course this could not be a definitive solution, cause it's ugly, but it's a good enough workaround for me. Also paste pictures in selection works again this way.

Hope it will be fixed within soon versions. thanks for your work!

EDIT: also checked on http://django-cms-demo-dotosaki-stage.us-iad-rs.aldryn.io/de/?edit , where i could confirm it.

**Comment by ferrix** [comment] 2016-02-05 14:01
I am having a similar problem. I cannot reproduce this in development. However the entire directory list table template does not seem to be rendered in the popup.

**Comment by lory87** [comment] 2016-04-27 07:36
@hersche @ferrix This issue is fixed in 1.2.0. I can't reproduce it anymore.

**Closed by lory87** 2016-04-27 07:36 UTC

**Comment by hersche** [comment] 2016-10-15 15:10
yep, seems to be done..
i was able to reproduce it via http:// while my nginx try to forward /admin/-stuff to https:// .
but this would be another issue (a proper "when admin then https://"-redirection in the cms would be nice).

thanks anyway, looks much nicer with dnd's and newer style.
