### ISSUE TITLE
IntegrityError at /admin/filer/folder/

### ISSUE THREAD

**Issue by psychok7** [divio/django-filer#754] opened 2016-02-26 16:33 UTC
So i have `django 1.8.9 and django-filer` and i started running into this problem 
```
insert or update on table "filer_clipboard" violates foreign key constraint "filer_clipboard_user_id_2b30c76f2cd235df_fk_auth_user_id"
DETAIL:  Key (user_id)=(67) is not present in table "auth_user".
```

I realizes it had something to do with a new Custom User i added but looking at filer source code i saw that is should deal with it as well

```
class Clipboard(models.Model):
    user = models.ForeignKey(getattr(settings, 'AUTH_USER_MODEL', 'auth.User'), verbose_name=_('user'), related_name="filer_clipboards")
```

i have `AUTH_USER_MODEL = 'authtools.User'` so it still didn't make sense so i had a look at the database and i found that my old constraint was still in place (it didn't update to my new user)

```
postgres=# \d filer_clipboard
                          Table "public.filer_clipboard"
 Column  |  Type   |                          Modifiers                           
---------+---------+--------------------------------------------------------------
 id      | integer | not null default nextval('filer_clipboard_id_seq'::regclass)
 user_id | integer | not null
Indexes:
    "filer_clipboard_pkey" PRIMARY KEY, btree (id)
    "filer_clipboard_e8701ad4" btree (user_id)
Foreign-key constraints:
    "filer_clipboard_user_id_2b30c76f2cd235df_fk_auth_user_id" FOREIGN KEY (user_id) REFERENCES auth_user(id) DEFERRABLE INITIALLY DEFERRED
Referenced by:
    TABLE "filer_clipboarditem" CONSTRAINT "filer_clipb_clipboard_id_335d159e1aea2cdc_fk_filer_clipboard_id" FOREIGN KEY (clipboard_id) REFERENCES filer_clipboard(id) DEFERRABLE INITIALLY DEFERRED
```

Any ideas on how i can fix this? Resorting to sql to remove the constrains and add the new one doesn't seem like the best approach.

**Comment by stefanfoulis** [comment] 2016-02-26 16:50
@psychok7 The problem is that at database level the constraints are not in sync with the new code. The db constraints get created at migration time, so you'd have to start off with a blank database and re-migrate the correct structure first. Then you might be able to restore a data backup onto it again (depending on your custom user model).

I didn't know about django-authtools, but looking through their docs (http://django-authtools.readthedocs.org/en/latest/how-to/migrate-to-a-custom-user-model.html#optional-step-5-customize : a bit outdated, these are for Django 1.6+South) it looks like a neat trick is to actually use the exact same user table as before, by setting ``db_table='auth_user'`` in ``Meta`` on your custom user model. That will mean that you are actually using the same table that already existed before. So all existing database level foreign key constraints to the User throughout your project will still reference the same table.
So first copy the user table over to your custom app (unchanged, just add the ``db_table='auth_user'``). Then make an initial migration. Then change the fields as you want them on your custom user object and make a new migration. ``--fake`` the first migration and migrate the rest. You should be all set.

Since this is not an issue with django-filer (as far as I can tell right now), I'll close this issue. Feel free to continue discussion here on the closed ticket. Or re-open if you feel there is something in django-filer that needs fixing.

**Closed by stefanfoulis** 2016-02-26 16:50 UTC

**Comment by psychok7** [comment] 2016-02-26 16:58
@stefanfoulis thanks for the response. 

Couldn't i just create some sort of datamigration and update the constraint instead? I don't know if its possible thats why i am asking (as an alternative to update the constraing via SQL). 

It just seems to me that it would be "easier" and "safer" so i dont't mess around with my production data

**Comment by stefanfoulis** [comment] 2016-02-26 17:06
@psychok7
yeah, a datamigration might work. I'm not sure how it works, but I guess you can just alter the tables from other apps within your migration. But you'll either have to hardcode all the constraints that need updating in the migration (which can be hard, depending on your codebase and how many 3rd party libraries you're using), or find some way to programmatically discover and iterate over all of them.

**Comment by psychok7** [comment] 2016-02-26 17:13
@stefanfoulis maybe with `RunSQL` in the datamigration.

I haven't had a similiar problem with other 3rd party apps yet only with filer .

**Comment by psychok7** [comment] 2016-02-26 18:22
@stefanfoulis i found another solution. setting `db_constraint=False` in all user foreign keys in filer applying the migration and then removing it again (since there are implications https://docs.djangoproject.com/en/1.8/ref/models/fields/#django.db.models.ForeignKey.db_constraint) automatically creates the new constraint that i need.

This is much better then writing sql manually since django does it for you.

I am still testing but so far its working no more error

**Comment by psychok7** [comment] 2016-02-27 17:58
i also added a data migration for the django_admin_log because it add a constraint pointing to the wrong place as well:

```
    operations = [
        migrations.RunSQL("BEGIN;"),
        migrations.RunSQL(
            "ALTER TABLE django_admin_log DROP CONSTRAINT "
            "django_admin_log_user_id_52fdd58701c5f563_fk_auth_user_id"
        ),
        migrations.RunSQL(
            "ALTER TABLE django_admin_log ADD CONSTRAINT "
            "django_admin_log_user_id_52fdd58701c5f563_fk_authtools_user_id "
            "foreign key (user_id) references authtools_user(id) "
            "DEFERRABLE INITIALLY DEFERRED"
        ),
        migrations.RunSQL("COMMIT;"),
    ]
```
