### ISSUE TITLE
SubjectLocation (FocalPoint) sometimes only appears on second pageload

### ISSUE THREAD

**Issue by stefanfoulis** [divio/django-filer#9] opened 2009-10-28 07:24 UTC

**Comment by lory87** [comment] 2016-04-27 08:27
Hi @szuliq I can't reproduce this issue anymore in current filer version 1.2.0. Do you still have this problem? Thank you for your feedback.

**Comment by szuliq** [comment] 2016-04-27 08:29
I will not be able to confirm this in a predictable time frame. Sorry.

Let's just assume it's working if you've checked with images that were loaded from browser's cache.

**Comment by lory87** [comment] 2016-04-27 08:35
@szuliq I have checked and it works fine. I will close this issue. If you will find this problem again please let us know. Thank you.

**Closed by lory87** 2016-04-27 08:35 UTC
Labels: bug
